### PR TITLE
the simpler rules

### PR DESCRIPTION
**Pull request by savili**
I have added three files:
MoreReplacementRules
XtaRules
DeletionRules01

They each contain a set of rules to be added to solomagic.py in the future

### CODE REVIEW

**Comment by aleixpol** [comment]
Why did you close it?

By the way, it lacks tests. :)

**Comment by savili** [comment]
Closing seemed the thing to do. Well, not really.

But I didn't dare hit any of the other buttons.

They looked a bit dangerous.

Shall I do it again?

 

I'll add tests!

 

Gesendet: Donnerstag, 19. Januar 2017 um 11:42 Uhr
Von: "Aleix Pol" <notifications@github.com>
An: aleixpol/solomagic <solomagic@noreply.github.com>
Cc: savili <s.abre@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [aleixpol/solomagic] the simpler rules (#2)


Why did you close it?

By the way, it lacks tests. :)

**Comment by aleixpol** [comment]
No, no, it's okay. I reopend it from the web UI, which is possibly a better way to interact with PR's because it looks a bit odd. xD

Now when you commit to your repository your commits will be added here.

**Comment by aleixpol** [comment]
Oh wow, that's quite some things!

**Pull request merged**
